import type { PipelineConfig } from "@pftypes/Pipeline.ts";
import type { Blueprint } from "@pftypes/Blueprint.ts";

// ── Lobster Workflow Generator ──────────────────────────────────────
// Generates Lobster state-machine YAML files where each step spawns
// an OpenClaw agent inside a container. The Lobster file acts as the
// workflow orchestrator — sequencing steps, piping data between them,
// and pausing at approval gates.
//
// Each step invokes:
//   openclaw agent --agent <name> -m "<prompt>" --json
//
// The agent config (model, tools, container sandbox) lives in
// openclaw.json — NOT in the Lobster file. This keeps the workflow
// definition declarative and the agent config centralized.

// ── Line Builder ────────────────────────────────────────────────────

class LineBuilder {
  private readonly lines: string[] = [];

  /**
   * Append a line with the given indentation level (2 spaces per level).
   *
   * @param indent - Number of indentation levels
   * @param line - The line content
   */
  add(indent: number, line: string): void {
    const prefix: string = "  ".repeat(indent);
    this.lines.push(`${prefix}${line}`);
  }

  /**
   * Append a blank line.
   */
  blank(): void {
    this.lines.push("");
  }

  /**
   * Return the accumulated output as a single string.
   *
   * @returns The complete output string
   */
  toString(): string {
    return this.lines.join("\n") + "\n";
  }
}

// ── Gate Set ────────────────────────────────────────────────────────

function buildGateSet(
  gates: ReadonlyArray<{ readonly after: string }>,
): ReadonlySet<string> {
  const set: Set<string> = new Set();
  for (const gate of gates) {
    set.add(gate.after);
  }
  return set;
}

/**
 * Generate a Lobster workflow YAML string where each step spawns an
 * OpenClaw agent inside a container.
 *
 * The workflow orchestrates step sequencing, stdin/stdout piping between
 * steps, and approval gates. Agent configuration (model, tools, sandbox)
 * is read from openclaw.json by the gateway — not embedded in the
 * Lobster file.
 *
 * @param pipeline - The pipeline configuration (step order, gates)
 * @param blueprints - ReadonlyMap of blueprint name to Blueprint
 * @returns A valid Lobster workflow YAML string
 *
 * @example
 * ```ts
 * const yaml = generateLobsterWorkflow(pipelineConfig, blueprintMap);
 * await writeFile("pipeline.lobster", yaml);
 * ```
 */
export function generateLobsterWorkflow(
  pipeline: PipelineConfig,
  blueprints: ReadonlyMap<string, Blueprint>,
): string {
  const out: LineBuilder = new LineBuilder();
  const gateAfter: ReadonlySet<string> = buildGateSet(pipeline.human_gates);

  let pendingGateId: string | null = null;

  // ── Header ──────────────────────────────────────────────────────

  out.add(0, `# ── ${pipeline.name} ──────────────────────────────────────────────`);
  out.add(0, "# Generated by pipelineforge sync --generate-lobster");
  out.add(0, "# Each step spawns an OpenClaw agent inside a container.");
  out.add(0, "# Agent configs (model, tools, sandbox) live in openclaw.json.");
  out.blank();
  out.add(0, `name: ${pipeline.name}`);
  out.add(0, `description: "${pipeline.description}"`);
  out.blank();

  // ── Args ────────────────────────────────────────────────────────

  out.add(0, "args:");
  out.add(1, "feature:");
  out.add(2, 'description: "Feature description or user story"');
  out.add(1, "repo_dir:");
  out.add(2, 'description: "Target repository directory"');
  out.add(1, "notes_dir:");
  out.add(2, 'description: "Notes/docs output directory"');
  out.add(1, "gateway_url:");
  out.add(2, 'default: "http://127.0.0.1:18789"');
  out.add(2, 'description: "OpenClaw gateway URL"');
  out.add(1, "skill_dir:");
  out.add(2, 'default: "~/.claude/skills"');
  out.add(2, 'description: "Path to Claude Code skill definitions"');
  out.blank();

  // ── Env ─────────────────────────────────────────────────────────

  out.add(0, "env:");
  out.add(1, 'CLAUDECODE: ""');
  out.add(1, 'ANTHROPIC_API_KEY: ""');
  out.blank();

  // ── Steps ───────────────────────────────────────────────────────

  out.add(0, "steps:");

  for (const bpName of pipeline.blueprints) {
    const bp: Blueprint | undefined = blueprints.get(bpName);
    if (bp === undefined) {
      continue;
    }

    out.add(1, `- id: ${bp.name}`);

    // ── Build the prompt message ──────────────────────────────────
    // The skill content is loaded via $(cat) and combined with
    // contextual variables (feature, repo, notes, prior outputs).
    const hasDeps: boolean = bp.depends_on.length > 0;
    const primaryDep: string | undefined = hasDeps ? bp.depends_on[0] : undefined;

    out.add(2, "run: >");
    out.add(3, "openclaw agent");
    out.add(3, `--agent ${bp.name}`);
    out.add(3, "-m");
    out.add(3, `"$(cat ${bp.skill_path})`);
    out.add(3, "");
    out.add(3, "## Feature");
    out.add(3, "${feature}");
    out.add(3, "");
    out.add(3, "## Repository");
    out.add(3, "${repo_dir}");
    out.add(3, "");
    out.add(3, "## Notes");
    out.add(3, "${notes_dir}");

    // Include prior step output as context
    if (primaryDep !== undefined) {
      out.add(3, "");
      out.add(3, "## Prior Output");
      out.add(3, `$${primaryDep}.stdout`);
    }

    out.add(3, '"');
    out.add(3, "--json");

    // ── stdin pipe from dependency ──────────────────────────────
    if (primaryDep !== undefined) {
      out.add(2, `stdin: $${primaryDep}.json`);
    }

    // ── when condition from pending gate ─────────────────────────
    if (pendingGateId !== null) {
      out.add(2, `when: $${pendingGateId}.approved`);
      pendingGateId = null;
    }

    out.blank();

    // ── Insert approval gate after this step if configured ──────
    if (gateAfter.has(bpName)) {
      const gateId: string = `approve-${bpName}`;
      out.add(1, `- id: ${gateId}`);
      out.add(2, "approval:");
      out.add(3, `prompt: "${bp.name} complete. Approve to continue?"`);
      out.add(2, `stdin: $${bpName}.json`);
      out.blank();

      pendingGateId = gateId;
    }
  }

  return out.toString();
}
